import SwiftUI

struct TransportCertificateChainView: View {
    let endpoint: URL?
    let certificates: [TransportCertificate]
    let capturedAt: Date?

    var body: some View {
        List {
            Section {
                Label("Accepted by iOS", systemImage: "checkmark.shield.fill")
                    .foregroundStyle(.green)
                if let endpoint {
                    CertificateValueRow(label: "Endpoint", value: endpoint.absoluteString)
                }
                if let capturedAt {
                    LabeledContent(
                        "Captured",
                        value: capturedAt.formatted(date: .abbreviated, time: .standard)
                    )
                }
                LabeledContent("Certificates", value: certificates.count.formatted())
            } footer: {
                Text("This is the certificate chain from the most recent authenticated WSS connection. The companion app does not replace or weaken Apple's system trust evaluation.")
            }

            ForEach(certificates) { certificate in
                Section(certificateTitle(certificate)) {
                    CertificateValueRow(label: "Subject", value: certificate.subject)
                    if let issuer = certificate.issuer {
                        CertificateValueRow(label: "Issuer in chain", value: issuer)
                    }
                    CertificateValueRow(
                        label: "SHA-256 fingerprint",
                        value: certificate.sha256Fingerprint
                    )
                    if let serialNumber = certificate.serialNumber {
                        CertificateValueRow(label: "Serial number", value: serialNumber)
                    }
                    if let notValidBefore = certificate.notValidBefore {
                        LabeledContent(
                            "Valid from",
                            value: notValidBefore.formatted(date: .abbreviated, time: .standard)
                        )
                    }
                    if let notValidAfter = certificate.notValidAfter {
                        LabeledContent(
                            "Valid until",
                            value: notValidAfter.formatted(date: .abbreviated, time: .standard)
                        )
                    }
                }
            }
        }
        .navigationTitle("Transport Security")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func certificateTitle(_ certificate: TransportCertificate) -> String {
        switch certificate.position {
        case 0: "Leaf Certificate"
        case certificates.count - 1: "Root Certificate"
        default: "Intermediate Certificate \(certificate.position)"
        }
    }
}

struct ThaneCertificateView: View {
    let agentName: String
    let material: PublicIdentityMaterial
    let certificate: X509CertificateEvidence

    var body: some View {
        List {
            Section {
                Label(
                    certificate.selfSigned
                        ? "Self-signed channel CA"
                        : "Channel CA certificate",
                    systemImage: "person.badge.key.fill"
                )
                LabeledContent("Certificate authority", value: certificate.isCA ? "Yes" : "No")
                LabeledContent("Self-signed", value: certificate.selfSigned ? "Yes" : "No")
            } footer: {
                Text("This public certificate is generated by \(agentName)'s Thane instance and committed in its signed core identity. It is separate from the HTTPS/WSS transport certificate.")
            }

            Section("Identity") {
                CertificateValueRow(label: "Subject", value: certificate.subject)
                CertificateValueRow(label: "Issuer", value: certificate.issuer)
                CertificateValueRow(
                    label: "SHA-256 fingerprint",
                    value: material.fingerprint
                )
                CertificateValueRow(label: "Serial number", value: certificate.serialNumber)
            }

            Section("Validity") {
                LabeledContent(
                    "Valid from",
                    value: certificate.notBefore.formatted(date: .abbreviated, time: .standard)
                )
                LabeledContent(
                    "Valid until",
                    value: certificate.notAfter.formatted(date: .abbreviated, time: .standard)
                )
            }

            Section("Algorithms") {
                LabeledContent("Identity format", value: material.algorithm)
                LabeledContent("Public key", value: certificate.publicKeyAlgorithm)
                LabeledContent("Signature", value: certificate.signatureAlgorithm)
            }
        }
        .navigationTitle("\(agentName) Channel CA")
        .navigationBarTitleDisplayMode(.inline)
    }
}

private struct CertificateValueRow: View {
    let label: String
    let value: String

    var body: some View {
        VStack(alignment: .leading, spacing: 5) {
            Text(label)
                .font(.subheadline)
            Text(value)
                .font(.caption.monospaced())
                .foregroundStyle(.secondary)
                .textSelection(.enabled)
        }
        .padding(.vertical, 2)
    }
}

#if DEBUG
#Preview("Transport Certificate Chain") {
    NavigationStack {
        TransportCertificateChainView(
            endpoint: PreviewFixtures.endpoint,
            certificates: PreviewFixtures.transportCertificates,
            capturedAt: Date().addingTimeInterval(-180)
        )
    }
}

#Preview("Thane Channel CA") {
    NavigationStack {
        ThaneCertificateView(
            agentName: PreviewFixtures.evidence.instance.name,
            material: PreviewFixtures.evidence.instance.channelCA,
            certificate: PreviewFixtures.channelCertificate
        )
    }
}
#endif
